name: Update data

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install python
        run: sudo apt-get install python3 python3-requests

      - name: Run python script
        run: python src/logger.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update data"
